### ISSUE TITLE
AuthoringToolID -  Optional?

### ISSUE THREAD

**Issue by gschleusner** [BuildingSMART/BCF-XML#103]
Hi,

I'm wondering how the Authoring Tool ID is option within the spec.   It would seem that this make implementation and reuse across platforms and different plugins very hard.  I was frankly surprised by this.  I was getting a team to get the Kubus Plugin in  for Navisworks and moving them back to Revit.  We have our own plugin that we like much  faster, and powerful but when we looked the AuthID was missing.  This means everyone has to implement their own crosswalk from IFCGUID to the native application ID ...I know certain elements in Revit make this hard so I'd be surprised if its possible in all systems.

This kind of thing would force us to use one vendors plugin vs being flexible...which is the whole point. Its not its not available in all the "checking tools" currently on the market.

Can someone explain the logic behind not making it mandatory.   I have been seeing a lot of "poor" implementations recently that break the standard. Like allow custom string in TopicStatus... I have no issue with "extensions" that add functionality but the core should be robust and standard.  

Greg

**Comment by pasi-paasiala** [comment]
The authoring tool id is not always present in IFC, It is not even possible to have it for some components, like space, in IFC. The id is specified in the tag attribute of IfcElement (http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcelement.htm). It is optional there and IfcSpace is not subclass of IfcElement (http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifcspace.htm).
