### ISSUE TITLE
Request to add Area as property for Topic

### ISSUE THREAD

**Issue by ErikPijnenburg** [BuildingSMART/BCF-XML#107]
We have got many users request for area as a topic-property for fitering issues. Is project specific geometrical part of the building like wing, sub-project, story, etc.

and added to the extension scheme lists enumeration values
enumeration value="Shops"
enumeration value="Offices"
enumeration value="Appartments"
enumeration value="General"

**Comment by ErikPijnenburg** [comment]
We remain with our proposal to add this as a simple extra (string-enumaration) property for filtering and sorting. Not to pack this now with extra's. That can be done later in BCF-API or leave that up to a hub.

**Comment by GeorgDangl** [comment]
See #115
