### ISSUE TITLE
Request to add Milestone as property of topic

### ISSUE THREAD

**Issue by ErikPijnenburg** [BuildingSMART/BCF-XML#108]
We offer Milestones in BIMcollab as topic proerty and got several users requests to be able to exchange this via BCF (XML/API). A Milestone consists of a name, start-date and completion-date.
Milestones can be used for the short cycles in a lean approache or for the buildingphases like preliminary design, final design, construction-preparation, etc, project specific.

**Comment by linhard** [comment]
For version 2.1 we introduced a new element "DueDate" on a topic. Regarding Eriks proposal wouldn´t it be an idea having this "DueDate" below "Milestone" ? So we would have then:
- Milestone
-- StartDate
-- DueDate
-- CompletionDate

**Comment by ErikPijnenburg** [comment]
Duedate should remain a property of the issue (to overrule Milestone end-dates per issue)
StartDate/CompletionDate are properties of a Milestone but we discussed to leave this type of properties for the BCF-API / up to a hub (compare other e.i. user-properties)

**Comment by GeorgDangl** [comment]
See #114
