### ISSUE TITLE
Multiple AssignedTo's for one topic?

### ISSUE THREAD

**Issue by ErikPijnenburg** [BuildingSMART/BCF-XML#109]
We have received BCF files created in Solibri where in the AssignedTo field of a topic were multiple users separated by comma's. I could not find this in the specification. I assume the definition allows only one AssignedTo user per topic ?

**Comment by linhard** [comment]
Yes, the definition allows only one AssignedTo user per topic. This is because we assumed, allowing multiple AssignedTo would mean that nobody is really responsible for the topic.

**Comment by GeorgDangl** [comment]
See #113
