### ISSUE TITLE
Appointment needed about viewpoint-changes

### ISSUE THREAD

**Issue by ErikPijnenburg** [BuildingSMART/BCF-XML#110]
There is no way to recognize if a viewpoint is modified in the current definition.
For the creation of a correct history on a hub (and to prevent sending unnessecary (sometimes heavy) viewpoint information when it was not modified) this information is needed. 

My suggestion is to appoint for BCF 2.1 that a viewpoint never changes when it has the same GUID:
- give the viewpoint a new GUID when it was modified
- a hub/client can count on no changes when it receives a VP GUID (and can do things like caching/ not sending, etc to optimize synchronization performance.

**Comment by GeorgDangl** [comment]
Hi Erik,

if the hub does implement the BCF API there's [caching via ETag](https://github.com/BuildingSMART/BCF-API#12-caching) built in. That's a standard Http functionality and tells you if the representation you currently have is still the one that's available at a given Uri (= Viewpoint Guid).

There's no such mechanism in BCF XML , and neither is there a `modified date` or `creation date` property for the viewpoint. So you're right, BCF XML change detection must be a full comparision.

However, I think we're too close to the release (which we've scheduled to do on Monday) as to make drastic changes at this point. But it's definitely something that should be looked further into.

**Comment by ErikPijnenburg** [comment]
I know, but we need it in BCF XML. It is easy to add an appointment.
This is the time for feedback of the new version, so to push a release through when discussions are still open is not good.

**Comment by ErikPijnenburg** [comment]
Decided in Telecon not to allow Viewpoint changes on same GUID. So when a Viewpoint changes it should get a new GUID: need to be put in the documentation.

**Comment by GeorgDangl** [comment]
See #112
