### ISSUE TITLE
Change Index types from "xs:integer" to "xs:int"

### ISSUE THREAD

**Issue by rubendel** [BuildingSMART/BCF-XML#111]
I would like to propose to use "xs:int" instead of "xs:integer" for the 2 index fields defined in markup.xsd, namely:

https://github.com/BuildingSMART/BCF-XML/blob/master/Schemas/markup.xsd#L38
and
https://github.com/BuildingSMART/BCF-XML/blob/master/Schemas/markup.xsd#L65

This will change the upperbounds and lowerbounds from respectively "infinite"/"infinite" [0] to "2147483647"/"-2147483648" [1]. I think this will be large enough for the purpose of indexing :).

The reason for proposing this is that it's easier to come up with a datamodel based on fixed bounds. For example Java will come with a BigDecimal type for this fields, where a simple integer would suffice.

[0] https://www.w3.org/TR/xmlschema11-2/#integer
[1] https://www.w3.org/TR/xmlschema11-2/#int

**Comment by GeorgDangl** [comment]
Good point! Fixed in d79abba
