### ISSUE TITLE
Suggestion: Use semver versioning

### ISSUE THREAD

**Issue by ottosson** [BuildingSMART/BCF-XML#116]
Is semver versioning something that could be interesting for BCF going forward?

http://semver.org/

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

**Comment by GeorgDangl** [comment]
Hi @ottosson,

while I'm a big fan of semver, I don't think it's an appropriate choice for an API specification. We'll likely not have fast iterations of the standard and even if, it's unlikely that there would be any `PATCH` versions.

**Comment by ottosson** [comment]
Fair enough =)
