### ISSUE TITLE
Viewpoints location

### ISSUE THREAD

**Issue by marache** [buildingSMART/BCF-XML#118]
Hi,

We have issues storing the location of the viewpoint (`CameraViewPoint`) when coordinates are expressed using geographic coordinates. 

Different cases are to take into account : 
- The coordinates are local supposed to be relative to an `IfcProject`; Not Ideal, since `IfcSite` contain the proper location (in longitude/latitude/height). If they are multiple `fcSite`, which one to use ? And the IFC file containing the `IfcProject` needs to be opened prior computing the viewpoint.
- The coordinates are world coordinates (absolute) ; There is a need to either always choose  longitude/latitude/height (like `IfcSite`) or specify the Spatial Reference System (string)

**Comment by GeorgDangl** [comment]
IFC files should only have one site, please reopen this issue if it's getting relevant again.

**Comment by mathieu** [comment]
Hi @GeorgDangl, I can't find any indication that an IfcProject (that IS unique) can't have multiple `IfcSite`s, if you could point me to the documentation location where this is specified ?

Even so, it doesn't invalidate the initial request about storing geographic coordinates for Viewpoints location ?
