### ISSUE TITLE
Color format

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-XML#122]
From here we can read the color should be in ARGB format: https://github.com/BuildingSMART/BCF-XML/tree/master/Documentation#components.

Could we perhaps give som examples of valid and invalid formats? Which formats for coloring are being used today?

**Comment by GeorgDangl** [comment]
ARGB / RGBA (RGB with Alpha) has an [entry on Wikipedia](https://en.wikipedia.org/wiki/RGBA_color_space) giving a bit of background info.

The way it's currently specified in #121 is:
`[0-9,A-F]{6}([0-9,A-F]{2})?`
which means sic (6) hex values and optionally two (2) more, so we can transport information about the RGB color values (6 hex chars = 3 bytes means 1 bytes per color channel) with an optional byte for transparancy / alpha.

I think that's quite a common color specification, seeing that [CSS is using that](http://www.w3schools.com/colors/colors_picker.asp#huecontainer), too.

**Comment by GeorgDangl** [comment]
Will addd this to the docs (also for the BCF API)
