### ISSUE TITLE
Feature Request : Identification of Time/Cost implications of a topic

### ISSUE THREAD

**Issue by phillipmcneill** [BuildingSMART/BCF-XML#129]
Hi all,

I'm new to this area but just wanted to raise an idea if it hasn't already been. We are using BCF/BIMCollab on a construction project and our contractor has recognised BCF as potentially a better kind of RFI (Request For Information), but missing a requirement to indicate whether a topic has time and/or cost implications - simply boolean capability (yes/no).

Any thoughts on this?

**Comment by lbj** [comment]
The TopicLabels are a pretty flexible way of resolving these kind of needs without resolving to hard coded attributes. I will assume that there are quite a few other factors that some projects would like to categorise on like environmental implications, health implications etc. Not only time and cost. By offering a way to filter topics on labels I guess your clients problem would be resolved.

**Comment by phillipmcneill** [comment]
Good point...I guess the BCF authoring tools can be structured to manage that at the project level.
