### ISSUE TITLE
Data analytics on BCF XML

### ISSUE THREAD

**Issue by PeterBorsje** [BuildingSMART/BCF-XML#150]
I want to be able to do data analitics on BCF data. 
From what I see in the schema's it is not possible to calculate the duration of the time that it takes to close an issue.

The <TopicStatus> is part of <Topic> and I am not able to see when this status changed.

**Comment by GeorgDangl** [comment]
Hi Peter,

you're right, a topic doesn't have an explicit property for that. You could use the `CreationDate` and `ModifiedDate` ([see here](https://github.com/BuildingSMART/BCF-XML/blob/release_2_1/Schemas/markup.xsd#L67-L69)) to get the data you want.

**Comment by PeterBorsje** [comment]
Hi Georg,

Does this ModifiedDate change when you add a comment?




Met vriendelijke groet,

ir. ing. Peter Borsje
Sr. Business Developer
Informatiemanagement
peter.borsje@engie.com
T +31 88 484 85 23
M +31 6 388 294 22

[Logo]<http://engie-services.nl/>



engie-services.nl<http://www.engie-services.nl>

ENGIE Infra & Mobility B.V.
Laan van Barcelona 800, 3317 DD Dordrecht
Postbus 8069, 3301 CB Dordrecht

Spaar het milieu door deze e-mail en de bijlagen niet af te drukken

**Comment by jasollien** [comment]
Hi Peter. The BCF file format is not optimal, when it comes to data analytics. But if you use the API, there is a seperate "history" resource, which will give you what you want. From here you can see all events that has happened on an issue, including "status change" events. https://github.com/BuildingSMART/BCF-API#491-get-topics-events-service

But, I fear it is not in production for alle vendors yet.
