### ISSUE TITLE
Snapshot images must be internal to BCF?

### ISSUE THREAD

**Issue by daveime** [buildingSMART/BCF-XML#152]
Is their any reason why DocumentReference and BimSnippet can utilize the isExternal flag to fetch the actual file data from an external source, but Viewpoint -> Snapshot images are forced to be internal to the BCF file structure?

Seems like a missed opportunity to keep the size of BCF files smaller and aid faster sharing / collaboration (especially on mobile/tablet platforms where bandwidth may still be an issue and snapshot image viewing could be an optional choice made by the user).

Any chance of this being implemented on a future release?

**Comment by jasollien** [comment]
I actually don't think anyone has brought up this issue yet, but I think it sounds like a great idea to have the possibility for external snapshots. Perhaps it can be added to the existing 2.1 without breaking the schema.

**Comment by denerlich** [comment]
I am looking for similar functionality to implement in the Autodesk Forge environment. Requirement is for user to create 1 issue by annotating and using illustrations from multiple documents ( PDF drawings and Models in the same Common Data Environment).
