### ISSUE TITLE
BCF 2.0/2.1 not backwards compatible with 1.0 due to bcf.version

### ISSUE THREAD

**Issue by LloydPickering** [BuildingSMART/BCF-XML#153]
Hi,

I am trying to work out why a product based on BCF 2.1 is not importing BCF 1.0 generated BCF file(s).

My research has led me to the bcf.version file. BCF 1.0 standard does not include a bcf.version file. BCF 2.0 and above require the file exists.

I would suggest that while bcf.version should be mandatory when written in 2.0 and above, it should be optional when read, and if not present, 1.0 assumed. This would restore compatibility with 1.0 files.

Lloyd

**Comment by GeorgDangl** [comment]
Hi Lloyd,

I think this must be handled by the importing application. During import, the app should identify which BCF version is read and then import that. You can not read BCF 1.0 files with the same code as BCF 2.0/2.1 files.
