### ISSUE TITLE
Discrepancy between 2.1 XML and API

### ISSUE THREAD

**Issue by nicktindall** [BuildingSMART/BCF-XML#154]
Hi All,

I just noticed there's a discrepancy between BCF 2.1 XML and BCF 2.1 API. In the API the comment has an optional field "reply_to_comment_guid" but there is no such field in the XML. In 2.0 comments have a ReplyToComment field, but that seems to have been dropped for 2.1 XML. Just wondering if that's an oversight or there's a reason for the discrepancy.

**Comment by GeorgDangl** [comment]
This was an oversight in the API. The property should be removed in the next release of the API as well.
See the issue in the [API repo](https://github.com/BuildingSMART/BCF-API/issues/155)
