### ISSUE TITLE
Additional annotation beyond lines

### ISSUE THREAD

**Issue by tldddd** [BuildingSMART/BCF-XML#157]
BCF can currently describe 3D annotation lines, but I was wondering if there has been much discussion around adding additional basic annotation features like text notes, dimensions, and clouds?

If not, I'd be happy to put together a basic schema to try and get the ball rolling?

**Comment by GeorgDangl** [comment]
Hey @tldddd, thanks for your feedback!

We've just had a conference call earlier today where we talked about this issue. At the moment, we won't add this to the BCF specification itself.

Our reasoning was that with every viewpoint, there is usually a snapshot (an image file) attached. It's a great idea to add some annotations to views, but most apps today do this in the snapshot, not in the model. We think allowing more elements beyond lines in the viewpoint would make the barrier for implementations higher, while the same functionality could be achieved with screenshots.

But we'll leave this issue open, we'd like to get more feedback!
