### ISSUE TITLE
Document reference: Id mandatory or not?

### ISSUE THREAD

**Issue by KevLoh** [buildingSMART/BCF-XML#158]
API says mandatory, XML says optional.

https://github.com/BuildingSMART/BCF-API/blob/release_2_1/Schemas_draft-03/Collaboration/DocumentReference/document_reference_GET.json

https://github.com/BuildingSMART/BCF-XML/tree/release_2_1/Documentation#documentreference-optional

API issue: https://github.com/BuildingSMART/BCF-API/issues/168

**Comment by GeorgDangl** [comment]
@KevLoh, can you submit a PR for this?
We've decided to make the Id in BCF XML also required.
