### ISSUE TITLE
Project's documents 

### ISSUE THREAD

**Issue by KevLoh** [buildingSMART/BCF-XML#159]
I wonder, how general documents are handled in XML.

For Rest/API, we have the Document(s) services (https://github.com/BuildingSMART/BCF-API#48-document-services).

For XML, I can't find any clear documentation. For DocumentReferences (https://github.com/BuildingSMART/BCF-XML/tree/release_2_1/Documentation#documentreference-optional) it says:

> DocumentReference provides a means to associate additional payloads or links with topics. The references may point to a file within the .bcfzip or to an external location.

That sounds as if internal documents can be everywhere in the bcfzip file.

When you read schema for DocumentReference, you'll find this
https://github.com/BuildingSMART/BCF-XML/blob/633f0f47338f69240e76b794255a36503e97d650/Schemas/markup.xsd#L98

I really wonder, if we need e.g. a seperate folder for projects documents and clearify, that internally documents **must** be placed there.

**Comment by GeorgDangl** [comment]
I'll append an information to the BCF XML spec that additional files can be placed within the BCFZip structure that are then referenced by other elements. These additional files are document references and are recommended to be placed in `Documents` in the root directory of the file.

**Comment by GeorgDangl** [comment]
Please see #164
