### ISSUE TITLE
The file extension "bcf"

### ISSUE THREAD

**Issue by amorch** [buildingSMART/BCF-XML#160]
The file extension "bcf" is introduced since BCFv2.1.

- Is it introduced in addition to "bcfzip", or is it mandatory to have the file ending "bcf" in 2.1?
- We already have markup.bcf. In my opinion it's not good practice to have the same file extension for two different file types (xml and zip).

**Comment by GeorgDangl** [comment]
Hi @amorch, we just discussed this in the BCF Hackathon. That's definitely something we'll look into for the next version. Xml files inside the zip container should just get the `.xml` extension.
