### ISSUE TITLE
Additional properties

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/BCF-XML#161]
Every now and then there are requests to add more information to topic, such as, [TopicArea](https://github.com/BuildingSMART/BCF-XML/issues/155). Often these are not very well defined and in discussions with different implementers it is hard to come to agreement whether to add them or not.
One possibility would be to have additional properties that could be attached to the topic. A bit like property sets in IFC. This needs to be carefully thought of, since it may have some unwanted consequences.

For adding these, I see the following:

Pros:
- Standard way to add and exchange information without adding vague content to the standard

Cons:
- May be very difficult to implement, since different sw would need to be prepared to display any additional properties
- It may turn into another BimSnippet, A feature in the standard, but not really used.
- In addition to property name and value, we should also specify its type, like "String", "Lenght", etc. This may get really complicated, if we need to have the same way of specifying the type as is in IFC.

**Comment by cschladetsch** [comment]
This issue seems to be stale/irrelevant. Can it be closed?

**Comment by GeorgDangl** [comment]
Hey @cschladetsch, we've added it to the _Release 4.0_ milestone, so it's stale for now but will be revisited for the next major version. It's something that comes up every now and then, and it's a valid use case.

For later reference, we could look how _catalogue references_ are implemented in the German GAEB standard as a way to reference arbitrary external information from within a BCF topic.

**Comment by GeorgDangl** [comment]
Tracked here: https://github.com/buildingSMART/BCF-API/issues/219
