### ISSUE TITLE
Document handling of decomposed objects in viewpoints

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/BCF-XML#167]
If all parts of a decomposed object, such as, curtain wall or assembly, only the parent component should be exported in BCF.
Currently this is the way it has been implemented, but this is not documented. It is only documented in one of the test cases: https://github.com/buildingSMART/BCF-XML/tree/release_2_1/Test%20Cases/v2.1/Visualization/All%20parts%20of%20curtain%20wall%20visible

**Comment by jasollien** [comment]
I think this change is good, but I am a bit diverted when it comes to introducing it before 3.0. Will research this a bit internally.

**Comment by pasi-paasiala** [comment]
Talked in Munich hackathon and agreed to change the documentation.

**Comment by pasi-paasiala** [comment]
https://github.com/buildingSMART/BCF-XML/pull/168
