### ISSUE TITLE
Allowing multiple values for the AssignedTo field

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-XML#169]
In todays BCF telecon, we discussed if the `AssignedTo` field in a topic should be allowed to hold multiple values. Currently, only a single person can be marked as being responsible for a topic.  
This issue should be used to discuss if this should be allowed in general and if yes, how it should be implemented.

**Pros** for allowing it include that such funtionality is already present in some tools, but a **con** is that it is generally considered more effective to have a single person / entity be responsible for any given topic in project management.

If this is going to be allowed, we will likely alter the `AssignedTo` field to be a list of values in the next BCF release. For the current version, an implementer agreement could be defined to use comma `,` or semicolon `;` separated values.

Additionally, it was proposed to make the `AssignedTo` field reference an user id explicitly. Currently, it simply refers the (singular) string value of the `UserIdType` in the extensions. This could be altered to return both an `UserId` (e.g. a Guid or a native identifier) as well as a `Username` (or an email).

After a decision, this will also have to be ported to the BCF API

* [ ] Decision - Do or Don't
* [ ] Implementation / Documentation
* [ ] Port to API

Please share your feedback!

/cc @jasollien @pasi-paasiala @ykulbak @pbuts @linhard @lindenthal

**Comment by ErikPijnenburg** [comment]
This has been discussed already for BCF 2x release; and back than it was decided to have one assigned-to user. See #109

**Comment by pbuts** [comment]
The reasoning of having one single person as responsible for the topic still seems valid to me.

For the identification of the responsible user we currently have a recommendation to use an email address and this appears to be widely implemented as such too.

There are good reasons to keep it this way or even better: make it a requirement to use the email address.
- it is readable without having to also implement a mapping from a guid or number to a human's name
- it is exchangeable: user x may be known in several systems with the same email address, guids or numbers will be very hard to match

I propose to make it a requirement to have a single AssignedTo person identified by email address by changing the UserIdType definition from generic string to an email address. The UserIdType applies to the creator and modifier of the topic too, so these will benefit from a solid and portable identification as well.

**Comment by nicktindall** [comment]
I feel like a single assignee is still appropriate, but I haven't spent a lot of time thinking about it since it was discussed last.
If we wanted to accommodate multiple assignees we could add an assignee cardinality property to project extensions meaning servers that supported multiple assignees could indicate as such.
However while this would work fine in the context of the API (and a single server), it would impact inter-operability in the event we exported a BCF ZIP from a tool that supported multiple assignees and attempted to import it into a tool that did not.

**Comment by LionelOnTech** [comment]
My preference is to keep a single assignee for the same reasons already specified. 

I agree that adding cardinality to project extensions would make sense. Though I see this as increasing the complexity for not much benefit.

I like the idea of having UserIdType defined explicitly. This removes ambiguity from the spec.
