### ISSUE TITLE
Product data within an BCF message

### ISSUE THREAD

**Issue by klacol** [buildingSMART/BCF-XML#170]
I would like to start a discussion about transporting product data as an IFC-Snippet with an BCF message. In a parallel repository, we work on the standardization of product data with IFC:

https://github.com/buildingSMART/ProductData

We use that repo to collect all sorts of sample files, either in the Step format or the XML format.

At the same time, a group of expterts within CEN (the european standardization organization) works on an implementers agreement for different types of product data as an EN or even ISO standard in ISO 16739 series.

The sample files in our repo are not yet well documented or even valid, but they are a collection of different approaches to express product requirement requests, product catalogues and selected products.

On feature, our group has in mind is, that some types of product data shoul be tranportable, and we would prefer to use BCF format as a "transporter".

Can anyone give me tips, if there is a way, to embed IFC files in an BCF message, and if this is the case, which requirements should such a file fullfil?

**Comment by GeorgDangl** [comment]
We're closing this issue because exchanging property data is being tracked by the "Properties Group" in the openCDE (Common Data Environment) project.
