### ISSUE TITLE
Filenames of snapshot and viewpoint

### ISSUE THREAD

**Issue by KevLoh** [buildingSMART/BCF-XML#179]
https://github.com/BuildingSMART/BCF-XML/tree/master/Documentation#topic-folder-structure-inside-a-bcfzip-archive

I guess, the mandatory filenames for snapshot and viewpoint (snapshot.png, viewpoint.bcfv) is due to some backward compatibility.

I'd vote for removing that restriction for next version. Or maybe there are other needs for this naming convention?

**Comment by GeorgDangl** [comment]
+1 from me for removing this convention! I'm not aware of any other technical restrictions for this besides backwards compatibility.

**Comment by GeorgDangl** [comment]
We've discussed this in todays telecon and decided to include this in the next release. This means we will drop the default filenames for the first viewpoints.

The default viewpoint should then be the first viewpoint in the topic, which is either indicated by it's `Index` property or by being the first in the list in the Xml file.

**Comment by ErikPijnenburg** [comment]
A definition like "the first viewpoint in the Xml file" is still vague. We use the viewpoint of the oldest comment as default viewpoint; for a user it is very usefull that the default viewpoint stays the same during the lifetime of the issue (unless user changes this on purpose)

**Comment by Moult** [comment]
Bump on this issue? As this determines whether I should change the test cases? (currently some test cases do not follow the mandatory snapshot.png naming rule - see https://github.com/buildingSMART/BCF-XML/pull/185)

**Comment by KevLoh** [comment]
@ykulbak Tried to add another PR: https://github.com/buildingSMART/BCF-XML/pull/242. Hope I used the correct workflow :-|
