### ISSUE TITLE
Clarify internal file references

### ISSUE THREAD

**Issue by hypirion** [buildingSMART/BCF-XML#180]
We at StreamBIM have noticed that some programs which export BCF 2.1 files sometimes use `\` for file separation, and sometimes uses the root folder as the working directory. We've also discovered that some tools uses the topic folder as working directory for some internal references, and the root folder for other references.

Looking into this, some examples in the BCF documentation uses [backward slashes](https://github.com/buildingSMART/BCF-XML/blob/b4abbf8a42309e5c7d0e94455f999301be9da097/Documentation/README.md#documentreference-optional), but at the end, it explicitly says that the forward slash is the path separator, and actual examples [uses those](https://github.com/buildingSMART/BCF-XML/blob/b4abbf8a42309e5c7d0e94455f999301be9da097/Test%20Cases/v2/Markup/PDFFile/8e46d831-4603-4bd1-ae0c-d1817ca50bf0/markup.bcf#L11). Bitmaps specify that the reference is the [_Name of the bitmap file in the topic folder_](https://github.com/buildingSMART/BCF-XML/blob/b4abbf8a42309e5c7d0e94455f999301be9da097/Documentation/README.md#bitmap-optional), although the single bitmap example uses [the root directory as working directory](https://github.com/buildingSMART/BCF-XML/blob/b4abbf8a42309e5c7d0e94455f999301be9da097/Test%20Cases/v2/Visualization/Bitmap/3f6ac03e-de8e-4c5e-b3f0-c7bf5f87fe51/viewpoint.bcfv#L25).

The way I've read the spec, internal BCF file references must be relative to the location of the file, and the file separator should be the forward slash `/`. If this is not the case, then I would suggest that this should be the standard across all internal file references, or at the very least that all internal file references have the same format and working directory.

**Comment by Moult** [comment]
Completely agree.

I have added this as an issue in my PR, to be discussed in the upcoming BCF meeting:

https://github.com/buildingSMART/BCF-XML/pull/185

Hopefully this can be resolved then.

**Comment by ykulbak** [comment]
Closed with the merging of pull request 185
