### ISSUE TITLE
Component Identification

### ISSUE THREAD

**Issue by an-ho** [buildingSMART/BCF-XML#182]
When listing a Component for visibility and/or selection, the Component is identified by the attribute "IfcGuid" and, optionally, the subtag "AuthoringToolId".

Problems arise when the object in question does not have an IfcGuid. And yes, there are still relevant BIM formats other than IFC out there.

My approach to this problem was simple: I did not write an "IfcGuid" attribute at all if I didn't have one, and gave the "AuthoringToolId" only.
Problem: **While this is allowed by the XML-Schema, the official manual says that it's not.**

It worked for a while, but recently, some software flat-out refused to import my BCFs if not all components had IfcGuids.
And I can not even blame them: It's what the manual says, although it's technically wrong.
I ended up generating fake IfcGuids for those cases - an ugly hack that hardly deserves the name of a "solution".

So this should be fixed.
The very least you should do is make the manual match the actual XML specification.
For the next version of BCF, I think you should even go a step further and get rid of the mandatory IfcGuid format altogether. It should be outside of BCF's scope what format the IDs are in as long as they are unique. This just needlessly limits the universal usefulness of the format.

**Comment by GeorgDangl** [comment]
Hi @an-ho, we've talked about this in the BCF Hackathon this week.

Generally, we see it the same as you:
1. The schema _does not_ require the `IfcGuid` to be present
2. The documentation, however, lists it as non optional -> this should be fixed in the documentation

As for supporting formats other than IFC, that's welcomed by the group. However, we see that that `AuthoringToolId` could be used for this.
If I understand you correctly, there are cases where you're
1. Not using an IFC format
2. The `AuthoringToolId` is the internal Id of the component in the design software
3. There's another Id present in the non-IFC exchange format, and you _can not_ use this for the IfcGuid property

Is this correct so far? Could you maybe provide a concrete example, maybe of a non-IFC model file that you'd like to reference and the handling for internal / external Ids in this format?

**Comment by ErikPijnenburg** [comment]
I strongly oppose against allowing non-IFC GUID's in the scheme !

That would be completely against the OpenBIM idea of BCF for application independent communication. Also it would reduce the willingness of non-IFC supporting applications to build better IFC / IFC GUID support.

**Comment by GeorgDangl** [comment]
Hi Erik,

do you mean that BCF should solely be focused on IFC models and not be used for other data exchange formats (e.g. native files, bills of quantities, GIS-data, CityGML...)?

**Comment by ErikPijnenburg** [comment]
BCF should focus solely on Open BIM formats, and not support any native/proprietary file formats. I beleive that doing the latter would trigger counter productive developments against our mutual goal with BCF to progress with (open) communication workflows.

**Comment by rasso** [comment]
I think we need to differentiate between communication and data-models. BCF is about supporting BIM-communication and a topic may have no direct relationship to a specific element in a model, or may have one. For the sake of users, BCF should not restrict communication to specific data models but should be as flexible as possible.
This said, certainly I strongly support data exchange based on open formats. But sometimes there are good reasons using other formats than IFC, and sometimes even proprietory formats. BCF should not hinder users to do so, if they have the need for this.

**Comment by an-ho** [comment]
I agree with Mr. Steinmann. While it certainly would be desirable for all BIM formats to use IfcGuids or at least GUIDs (which would be easily transcribable), it's just not the world we live and work in. Our approach for DESITE is to make the best of all the model formats we get - even those we personally don't like. Our customers often have their long-established workflows which they can't easily change just because we say so.
One could deny those customers BCF support just to teach them a lesson... but to me, that flies in the face of the "open" concept.
Also, as I have already written in my opening post, for a BCF to do its job it is really not important what format an ID comes in as long as it uniquely identifies objects.

That being said...
Georg, you asked for an example. Here is one.

```xml
  <Components>
    <Selection>
      <Component>
        <OriginatingSystem>DESITE</OriginatingSystem>
        <AuthoringToolId>LoD1_566_5932_1_HH_LoD1_566_5932_1_HH_41-8f1e-fab5070106bc_Block</AuthoringToolId>
      </Component>
      <Component>
        <OriginatingSystem>DESITE</OriginatingSystem>
        <AuthoringToolId>LoD1_566_5932_1_HH_LoD1_566_5932_1_HH_36-b559-ba095e7b401a_Block</AuthoringToolId>
      </Component>
    </Selection>
  </Components>
```

Please let's not talk about those IDs. Yes, they're awful. But it's the data we get.
Now what I used to do is to write the BCFs as above: Without an IfcGuid attribute on the Component tag.

For clarification: This works for me. I have no problem with this. And it validates against the XML schema.

The problem is that there's BIM software out there (Allplan being one) which chokes on this because they always expect an IfcGuid. So I would like to tell them "look, you're doing it wrong, BCF allows the IfcGuid to be missing". But unfortunately I can't, because BCF is ambiguous on this point.
So what I did instead is generate fake IfcGuids. With those, the importing software obviously can't find any objects, but at least the process doesn't fail entirely and things like the camera position are still usable:

```xml
  <Components>
    <Selection>
      <Component IfcGuid="1FAXOgAzAzLBgUYrycpbcf">
        <OriginatingSystem>DESITE</OriginatingSystem>
        <AuthoringToolId>LoD1_566_5932_1_HH_LoD1_566_5932_1_HH_41-8f1e-fab5070106bc_Block</AuthoringToolId>
      </Component>
      <Component IfcGuid="3FRcGZ6dWXh6cF9Egcpbcf">
        <OriginatingSystem>DESITE</OriginatingSystem>
        <AuthoringToolId>LoD1_566_5932_1_HH_LoD1_566_5932_1_HH_36-b559-ba095e7b401a_Block</AuthoringToolId>
      </Component>
    </Selection>
  </Components>
```

I generate these IfcGuids from a hash of the AuthoringToolId. The trailing "cpbcf" is a hint to myself that these IfcGuids are fake.
I'd really like to **not** have to keep doing it this way.

**Comment by GeorgDangl** [comment]
We're going to do the following:
* The README is updated to state that the IfcGuid itself is optional (https://github.com/buildingSMART/BCF-XML/tree/release_2_1/Documentation#component)
* The README should be appended with a small snippet to explain this. While the main use case of BCF is to use Open BIM models that have IfcGuid properties for their components, it can also be used for native models or other data types that don't have a concept of IfcGuids
* Either IfcGuid or the AuthoringToolId should be present, as an identifier for a component should always be given

@an-ho: Could you also provide us with the use case behind this, and maybe with an example where you'll have a BCF referencing components that don't have an IfcGuid?

**Comment by GeorgDangl** [comment]
CC @SimonDaum

**Comment by an-ho** [comment]
@GeorgDangl : Thanks for the update. As for providing the use case + example, I believe I did that in my last post from 2019-05-17: It's when you want to offer BCF functionality with model data that has weird (non-GUID) IDs (for whatever reason). The specification should be clear then if I am allowed to use another ID format in IfcAuthoringToolId, omitting IfcGuid, or if I basically have to say "sorry, your model is incompatible to BCF workflows".
Whatever the decision, schema specification and documentation should agree on this, which they currently don't.

**Comment by ykulbak** [comment]
@an-ho regarding the use case, can you please tell us which tools/vendors exchange the information? we can see that DESITE is where the viewpoints originate from but it's not clear who consumes the topics?

It's not common to see two vendors using BCF to exchange topic information but not using IFC to exchange the models. The information would allow us to confirm that we're not changing the standard for a "closed loop" within a single vendors ecosystem of products.

**Comment by an-ho** [comment]
@ykulbak 
> It's not common to see two vendors using BCF to exchange topic information but not using IFC to exchange the models.

You are not wrong, this has indeed become a lot less common since I opened the discussion. Still, it hasn't become entirely irrelevant, for example for Revit dwf/x or iTWO cpixml. Especially the later has sometimes really weird part IDs.

> The information would allow us to confirm that we're not changing the standard for a "closed loop" within a single vendors ecosystem of products.

First of all, my core request was never about changing the standard, but defining it properly and unambiguously, since the XML schema definition allows missing IfcGuids while the documentation does not. This kind of inconsistency invites incompatibilities in implementations. Georg wrote that the documentation will be changed accordingly, which would fix this general issue.

That being said, I'd still be in favor of not restricting the ID format as that is just not necessary for BCF to work properly. I still haven't heard a reason for it apart from promoting IFC use. While I kinda understand that goal from buildingSmart's POV, it shows that you and I have very different definitions of the word "open". While for you it apparently means "we only play with IFC", to me it would mean to play with everyone - even the evil proprietary formats.
Which is why your wording is remarkable. It is you - not me - who is arguing in favor of a "closed loop" here.

**Comment by ykulbak** [comment]
@an-ho can you please tell us which tools/vendors exchange the information?

**Comment by an-ho** [comment]
1. RIB iTWO and their Revit plugin, as stated. (What we often see there is a namespace prefix on a GUID, which can be removed but can lead to collisions when assembling coordination models).
2. Models that are not BIM models by a strict definition of the term: DWG plan underlays, CityGML, Alignments, Point Clouds, etc.
3. Generally any tool, past, present or future, that doesn't use IfcGuid or GUID as mandatory format.

You may consider 1. as niche, 2. as irrelavant, and 3. as undesirable. **That's fine.** (Not my personal definition of "open", but that is really just IMO).
If you want to restrict BCF to IFC, by all means do so, just be clear about it.
In the schema, just change
`<xs:attribute ref="IfcGuid"/>`
into
`<xs:attribute ref="IfcGuid" use="required"/>`
and be done with it.
(This would make the "AuthoringToolId" completely useless, but since it's optional already, it doesn't matter. I wonder why you have it in the first place if anything but IFC should be forbidden anyway.)

Either make that small change to the XSD, **or** let the documentation state that "IfcGuid" is optional, which **it is** by current XSD definition.

All I ask is that you deliver a consistent and non-contradictory description of your own format, for crying out loud.
I don't see how this is rocket science and I feel that we are just moving in circles here.
I rest my case. Do what you want. I have explained my point of view several times over by now and if you don't want to see it, then don't.

**Comment by GeorgDangl** [comment]
Hey @an-ho, thank you for your input. I don't think we should let this discussion escalate, the points are clear.

We'll cover this in the next call on Monday. From my point of view, I think it makes sense to simply update the documentation so that it states that the `IfcGuid` is an optional field, and omitting it and providing and authoring tool id instead would let users reference any arbitrary element in any format.
I see the general use case for that, it's just that currently, BCF is strictly for referencing building models and there's usually always an `IfcGuid` available, but this could change in the future with a wider adoption of the standard.

**Comment by ykulbak** [comment]
@pasi-paasiala please review/merge the linked pull request
