### ISSUE TITLE
Should a pixel resolution be specified for snapshot.png?

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#186]
Currently no pixel resolution is mentioned in the specification for snapshot.png.

I propose that perhaps one should be recommended (only recommended, not "required"), to prevent potential ultra-high-res images to be created that may bloat imports, exports, app performance, and REST calls.

To begin the discussion, I will recommend a maximum width or height of 800px - a balance between not being too large, being able to be displayed at full res at most modern computers without clipping, and still being large enough to see details in models.

**Comment by CBenghi** [comment]
In the Hackaton call today there's anecdotal evidence that some enforcement is done, but the value is around 1500x1500 px.

**Comment by GeorgDangl** [comment]
Current discussion from call, unsorted:
Recommendation to update the spec to say that snapshots should not be too large. This is more an UX issue
than a technical limitation.
KUBUS limits images width / height to 1500 px.

Option to return thumbnails in BCF API for snapshots. -> PR by Georg
Servers should offer a "reasonable size" for the thumbnails, as devices can always adjust the size smaller
for displaying purposes. This means servers can precompute thumbnails for bandwidth optimized serving.
-> Separate resource for thumbnail, e.g. (by Yoram):
https://bim.aconex.com/bim/api/projects/1879048400/views/84f970bf6ff142d1be7351973676729d/snapshot
https://bim.aconex.com/bim/api/projects/1879048400/views/84f970bf6ff142d1be7351973676729d/thumbnail?width=120&height=68
The second is a thumbnail
-> Thumbnail support should be indicated this way: https://github.com/buildingSMART/BCF-API#415-expressing-user-authorization-through-project-extensions

**Comment by GeorgDangl** [comment]
We'll update the spec with something like "the longest dimension should not exceed 1500 px". Workarounds could be to include larger images as documents that can be loaded on demand.
