### ISSUE TITLE
Colour hexes should probably allow both uppercase and lowercase

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#187]
Currently the visinfo.xsd enforces a regex for the colour of [0-9,A-F] - that is, uppercase.

Some test cases use lowercase hex.

I am not aware of any particular case sensitivity for hex representations. changing the spec to allow lowercase seems to be sensible, and i do not think it will break any implementation. if there is a reason to enforce uppercase, i am also happy to fix the test cases.

Quote from @pasi-paasiala on Slack:

> @Dion Moult That is interesting. I looked at spec of BCF-XML 2.0 and there it is specified as xs:hexBinary. That seems to be using lower case. The reason for changing that must be that in 2.1 the length is restricted.
> @Pieter This seems to be your modification. Do you remember if there's a reason to use only upper case?

**Comment by GeorgDangl** [comment]
The regular expression should just be updated:
https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/visinfo.xsd#L155
Probably an oversight in the original definition.
