### ISSUE TITLE
Proposal to reference external URIs for schema definitions for core specification

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#188]
There is inconsistency around how schemas are referenced in XML output in the test cases. As a small demonstration, consider the `bcf.version` file, which is arguably the simplest file possible in the BCF specification. The standard states the following content:

```
<Version VersionId="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="version.xsd">
```

This suggests a `version.xsd` available in the cwd, but this file is not packaged in any of the BCF test cases.

Similarly, many test cases make references (albeit seemingly incorrectly, by applying the `xsi:schemaLocation` attribute, but the intention is there) to other `*.xsd` files like `markup.xsd` and `project.xsd` and `visinfo.xsd` but these are never packaged with the BCF.

I propose to revise as follows (note: Github links show the intention, but it may be hosted elsewhere, say the buildingSMART website).

In `bcf.version`:

```
<Version VersionId="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/buildingSMART/BCF-XML/release_2_1/Schemas/version.xsd">
```

In `project.bcfp`:

```
<ProjectExtension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/buildingSMART/BCF-XML/release_2_1/Schemas/project.xsd">
```

In `markup.bcf`:

```
<Markup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/buildingSMART/BCF-XML/release_2_1/Schemas/markup.xsd">
```

In `viewpoint.bcfv`:

```
<VisualizationInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/buildingSMART/BCF-XML/release_2_1/Schemas/visinfo.xsd" Guid="21dd4807-e9af-439e-a980-04d913a6b1ce">
```

This proposal does _not_ mandate implementations to parse the schema location URI, download it, and validate it. Implementations are free to choose their approach - they may bundle their own XSD files an choose to ignore that field if they want to, they may download and cache it, or they may completely ignore XSD validation whatsoever.

Thus the benefits of this approach:

 - Improves consistency by pointing to a single source of truth
 - Decreases filesize (assuming people package the xsds in the first place)
 - Create more legal XMLs, if people care about it :)
 - By not having any mandate around implementers parsing it, implementers are free to be as lenient as possible still, but at the same time, they now know what the "source of truth" is :)

**Comment by GeorgDangl** [comment]
This is to ensure that generated BCF XML files have a reference to their original Xsd, to help identify the Xml files. This reference should
also be directly embedded in bcf.version on https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Documentation/bcf.version.
The referencing of the namespaces or schema files should be explained in the README, and the test cases should be updated to reflect the changes.

**Comment by GeorgDangl** [comment]
I'll update the links to the `release_2_2` branch when @ykulbak has created the branch.
