### ISSUE TITLE
isExternal should be CapsCase

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#189]
The documentation refers to the attribute IsExternal in CapsCase.

The specification defines it as isExternal in camelCase.

All element and attribute names in the specification are CapsCase, except for isExternal, which breaks the convention. If I were not concerned for case sensitive vendor implementations, I would push for standardising CapsCase.

I propose for this to be fixed in BCF v2.2, by requiring CapsCase.

**Comment by GeorgDangl** [comment]
Should be easy to change, accepted for the next version.
