### ISSUE TITLE
Mandate lowercase UUIDs in topic names

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#190]
The documentation for BCF-XML does not specify the case sensitivity of UUIDs.

This is very important, because on Unix systems (yes, BIM work is done on Linux and Mac too!) file paths are case sensitive.

Out of all the v2.1 test cases provided in the repo, most are lowercase, 5 out of 33 occurrences of a UUID are upper case - the rest (majority) are lowercase.

The official specification for UUID specifies lowercasem see: https://stackoverflow.com/questions/8258480/type-of-character-generated-by-uuid

> 6.5.4 Software generating the hexadecimal representation of a UUID **shall not use upper case letters.** NOTE – It is recommended that the hexadecimal representation used in all human-readable formats be restricted to lower-case letters. Software processing this representation is, however, required to accept both upper and lower case letters as specified in 6.5.2.

I have checked the primary source of that answer and verified that it is in the specification.

As for the note for software processing UUIDs - that's fine and all, but we're talking about a fundamental fact of Unix filesystems here, which is not built to process UUID dir names in any way :)

It is possible for implementers to work around the case insensitivity on Unix, by listing all dirs and checking in a case insensitive way, but considering that BCF can hold hundreds of thousands of issues, this sounds like a particularly inefficient solution instead of enforcing a bit of discipline in the spec :)

**Comment by GeorgDangl** [comment]
Accepted for the next version.
