### ISSUE TITLE
Clarification required on ViewToWorldScale definition

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#191]
The current definition I am assuming is:

```
if viewpoint is landscape:
    view_scale = horizontal_viewpoint_dimension
else:
    view_scale = vertical_viewpoint_dimension
world_scale = view_scale * view_to_world_scale
or put another way...
view_to_world_scale = world_scale / view_scale
```

So for a perfectly square viewpoint, with a `ViewToWorldScale` of `1`, a 1m x 1m square centered on the viewpoint will fit perfectly within the viewpoint.

Similarly, if I change the `ViewToWorldScale` to `2`, i can perfectly fit _two_ 1m x 1m squares next to each other within the viewpoint.

This a pretty standard definition in the CG world, and it would be good to mention it explicitly (perhaps with better wording) in the documentation.

**Comment by Moult** [comment]
Pinging @teocomi  and @theoryshaw who previously mentioned this ambiguity in #11

**Comment by teocomi** [comment]
Unfortunately, I've been out of the loop for the past few years so can't add much to the conversation, but thanks for picking it up!

**Comment by GeorgDangl** [comment]
Will be decided tomorrow or next Monday, after checking back with other experts.

**Comment by ykulbak** [comment]
We don't object to this interpretation - seems very reasonable. But since Aconex only supports perspective viewpoints we'd like implementers who have orthogonal camera support to weigh in.

**Comment by GeorgDangl** [comment]
@cbenghi will make a small proposal to clarify this in the spec.

**Comment by ykulbak** [comment]
Clarified by #227. Thank you @CBenghi !
