### ISSUE TITLE
Clarification required on ClippingPlane direction

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#193]
Does this direction vector point in the direction where things are visible, or in the direction where things are invisible (i.e. clipped)?

I am following the convention established in the CG industry, for example in Sketchup, the +Z local axis (or positive normal direction) of the clipping plane is unclipped, and the -Z or negative normal is clipped. I therefore assume that this direction points in the positive normal direction.

Rhino also follows [the same convention](https://docs.mcneel.com/rhino/5/help/en-us/commands/clippingplane.htm).

It would be good to clarify and update the documentation.

Picture of SketchUp below.

![](https://blender.community/api/storage/file/59/59ee2b501de2fb001513f45c/74/740aee487de847ae8d5170fd106a3839-l.jpg)

**Comment by GeorgDangl** [comment]
The direction should be included in the readme.

**Comment by ykulbak** [comment]
In Aconex, the direction vector points in the direction where things are _invisible_. I've tested with Solibri who seems to do the same.

**Comment by Moult** [comment]
So we have an inconsistency in implementations. We should tabulate the results, perhaps weighted in some way by number of users or other metric, and decide which way to go.

 - Sketchup: Positive = Visible
 - Rhino: Positive = Visible
 - Blender: Positive = Visible
 - Aconex: Negative = Visible
 - Solibri: Negative = Visible
 - XBimXplorer: Negative = Visible
 - BimSync: Doesn't seem to apply
 - Revit: Doesn't seem to apply
 - ArchiCAD: ?
 - IFC: No concept of section planes

I am happy to go either way personally. I see equal argument with the current results to go either way.

If others can test other programs that would be good.

**Comment by GeorgDangl** [comment]
We'll use the convention that the negative side is the visible side, since that's what most applications already do.
