### ISSUE TITLE
Height of Bitmap is unclear

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#194]
The schema talks about the height of bitmaps, but the documentation does not mention this. Can I propose to modify the documentation to mention the height, as well as clarify that like everything else in the documentation, it follows meters as a fixed unit?

**Comment by GeorgDangl** [comment]
The height should be in _meters_, and this should be included here: https://github.com/buildingSMART/BCF-XML/tree/release_2_1/Documentation#bitmap-optional

Alignment with the BCF API should also be considered.
