### ISSUE TITLE
Bitmap should be Bitmaps in schema

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#195]
In the following line, it doesn't follow the same plural / single convention of the rest of the schema. This:

 1. Creates inconsistencies - there is `<Lines><Line>...</Line><Line>...</Line></Lines>` but for bitmap it is just `<Bitmap>...</Bitmap><Bitmap>...</Bitmap>`
 2. Not illegal from a parsing point of view, but very strange because the bitmap format entity is also called `<Bitmap>`. `<Bitmap><Bitmap>...</Bitmap></Bitmap><Bitmap><Bitmap>...</Bitmap></Bitmap>`

https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/visinfo.xsd#L28

**Comment by GeorgDangl** [comment]
The `Bitmap` array element itself should be wrapped in a `Bitmaps` (note the trailing plural _s_)
element. Additionally, inside a `Bitmap` element, the format should be renamed to `Format` so it's
not the same as the parent elements name.

**Comment by GeorgDangl** [comment]
Info from the call:

````xml
<Viewpoint>
  <Guid>123</Guid>
  <Bitmap>
    <Bitmap />
  </Bitmap>
  <Bitmap>
    <Bitmap />
  </Bitmap>
</Viewpoint>

-->

<Viewpoint>
  <Guid>123</Guid>
  <Bitmaps>
    <Bitmap>
      <Format />
      <Reference />
    </Bitmap>
    <Bitmap>
      <Format />
      <Reference />
    </Bitmap>
  </Bitmaps>
</Viewpoint>
