### ISSUE TITLE
Comment text should not be empty

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/BCF-XML#196]
The specification currently requires comments to have a \<comment\> (text) element but doesn't enforce it's length to be greater than zero. I suggest adding a clarification that the comment element should always have text.

**Comment by GeorgDangl** [comment]
We'll update the schema to make it clear that a comment can not be empty.
Both the schema and docs should be updated, also for the BCF API.

**Comment by GeorgDangl** [comment]
We're keeping it as it is😊

**Comment by GeorgDangl** [comment]
We will clarify that the `Comment` property is optional (in the schema and the documentation), but we should add clarification that either the `Comment` or `Viewpoint` property should be present to ensure the comment serves a purpose.

**Comment by CBenghi** [comment]
Just for context, 
the outcome was determined by the need to have a way to store the `date` for `viewpoints`. 
Viewpoints currently lack date, an adopted workaround is to add a comment with no text.
So to deal with those scenarios it would not be safe to add the restriction.

We'll probably add `date` to viewpoints in version 3, and this can be reconsidered.
