### ISSUE TITLE
XML DateTime values should default to UTC when no timezone is specified

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/BCF-XML#197]
The XML Schema DateTime type has no default timezone associate with it (I think). Any objection to adding to the specification that XML DateTime values should default to the UTC timezone when no timezone is specified?

**Comment by GeorgDangl** [comment]
I think that’s a good idea.

**Comment by GeorgDangl** [comment]
We should also update the documentation with a guideline that says that when serializing date values, they should include a timezone.

**Comment by GeorgDangl** [comment]
CC @CBenghi
