### ISSUE TITLE
Extension-schema example does not work

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#198]
For the first time, I actually tried parsing the extension schema. (https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Extension%20Schemas/extensions.xsd)

I got a few errors.
1: "SnippetType" is not a field in markup.xsd (it is located under BimSnippet), and hence the xsd validator complains about it missing. I suggest to remove it

![image](https://user-images.githubusercontent.com/3275463/85015364-21ccb380-b168-11ea-8bd6-fb6ad8353427.png)

2: Cannot find the types from base attribute on restriction tag.
Example: <restriction base="TopicType">
![image](https://user-images.githubusercontent.com/3275463/85015328-14172e00-b168-11ea-9d34-2e1acda397a1.png)

Parser complains that TopicType is missing (same for all types). I solved it by using "string" instead of "TopicType".

3: Gets "undefined simple or complex type 'TopicType'" error for all bottom elements:
![image](https://user-images.githubusercontent.com/3275463/85015298-08c40280-b168-11ea-890b-f78b503084b7.png)

Would be nice to get your feedback on this. Anyone actually parsing this file? Do I perhaps have the wrong setup on my xsd parser (Using XSOMParser)?

**Comment by GeorgDangl** [comment]
A breaking change, but for 3.0 we've decided to remove the `extensions.xsd` in its current form and replace it with a plain XML file that just contains lists of allowed value for certain properties.
