### ISSUE TITLE
Clarify that a viewpoint can have either a perspective camera or an orthogonal camera but not both

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/BCF-XML#199]
The XML schema allows providing both perspective and orthogonal camera in the same viewpoint .

**Comment by GeorgDangl** [comment]
It's defined here:
https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/visinfo.xsd#L11-L12

@ykulbak suggests to look at the xsd `choice` element.
