### ISSUE TITLE
Document references should be wrapped in a container and use plural form

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-XML#208]
Similar to #195, see: https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/markup.xsd#L77-L87

**Comment by GeorgDangl** [comment]
Also https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/markup.xsd#L61 (`ReferenceLink`).

**Comment by GeorgDangl** [comment]
CC @ykulbak

**Comment by ykulbak** [comment]
Implemented by #225
