### ISSUE TITLE
Documents should be according to the BCF-API specification

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#224]
Hi all, I am currently trying to implement importing documents using BCF-xml v2.1, and see some big drawbacks, compared to the BCF-API v2.1.

In BCF-API, you are able to send the guid of a new document, so that it can persist in the BCF roundtrip. This is not possible in the current version of BCF-xml, as documents do not have any guid. 

My suggestion is that all documents should be listed at project level, maybe in project.xsd, where each document has a fileName and a guid. Ideally also some additional fields, but we can postpone that for later.
I also suggest that the file name of each document file should be the document guid, and stricly saying that all documents should be located in the folder "Documents", not just recommending it.

In the documentReferences, we then only need the guid of the document, instead of the path to the file.

Please let me know if you have some feedbacks.

**Comment by jasollien** [comment]
https://github.com/buildingSMART/BCF-XML/pull/225

**Comment by jasollien** [comment]
@ykulbak, @GeorgDangl: Hope we can look at this issue next week.

**Comment by ykulbak** [comment]
@pasi-paasiala suggested in the group discussion to communicate documents in a dedicated `documents.xml` file.

**Comment by ykulbak** [comment]
Implemented by #225
