### ISSUE TITLE
Add server_id

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/BCF-XML#233]
Since Topic Index is deprecated (https://github.com/buildingSMART/BCF-API/issues/202), we should add support for server_id also in BCF-XML.

Acceptance criteria
_____
[ ] server_id is available in BCF-XML
[ ] Index deprecation documentation refers to the server_id property

**Comment by jasollien** [comment]
Had a comment regarding this: https://github.com/buildingSMART/BCF-XML/issues/232#issuecomment-732063811

**Comment by ykulbak** [comment]
Closing, duplicate of #232
