### ISSUE TITLE
Change next version from 2.2 to 3.0

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/BCF-XML#241]
- [x] Find and replace any content reference pointing to 2.2 with 3.0 (examples?)

**Comment by cschladetsch** [comment]
Are there any links that speak to the rationale for this change from a point release to a major release?

**Comment by cschladetsch** [comment]
Are there any links to the rationale for changing this from a point release to a major release?

**Comment by ykulbak** [comment]
closed by #247
