### ISSUE TITLE
Comments collection in plural

### ISSUE THREAD

**Issue by emaschas** [buildingSMART/BCF-XML#266]
Could you please rename the collection of "Comment" in the "Markup" element in plural to avoid confusion and to be consistent with "Viewpoints".

<xs:element name="Markup"> 
	\<xs:complexType\>
		\<xs:sequence\>
			<xs:element name="Header" type="Header" minOccurs="0"/>
			<xs:element name="Topic" type="Topic"/>
			<xs:element name="Comment" type="Comment" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Viewpoints" type="ViewPoint" minOccurs="0" maxOccurs="unbounded"/>
...
like this :
			<xs:element name="Comments" type="Comment" minOccurs="0" maxOccurs="unbounded"/>

Thank-you.

**Comment by cschladetsch** [comment]
The truth is, these changes around containers in the Schemas result in some ugly-looking code:

`List<Viewpoint> viewpoints = topic.getViewpoints().getViewpoint()`

Note that we move from a plural (getViewpoints) to reach a non-plural (getViewpoint) to get a sequence (which is a plurality). This is confusing.

It's all backward-reading. I understand the intention for wrapping the containers in a top-level element, but it results in confusing and un-intuitive code from the Schema in practice.

Unsure what the best way forward is. Just commenting that the current schema results in confusion, to the point where people that review my code ask if it's "Really the standard?", and then ask me to rationalise why it is the way it is.

I find it hard to answer other than "It makes sense topologically". 

Specifically, to add a new Viewpoint in code:

`topic.getViewpoints().getViewpoint().add(newViewpoint(....)));`

**Comment by cschladetsch** [comment]
What reads better (in code) to me is something like:

`topic.getViewpoints().getInstances().add(newViewPoint(...));`

**Comment by emaschas** [comment]
It reads better to have :
foreach(Comment com in topic.Comments) {...}
rather than the actual :
foreach(Comment com in topic.Comment) {...}

**Comment by emaschas** [comment]
And I agree that ViewPoints should be changed in Viewpoints for consistency...

**Comment by emaschas** [comment]
Closed after #267

**Comment by emaschas** [comment]
I withdraw my Pull request, but the discussion may continue... (sorry for closing too fast).

**Comment by emaschas** [comment]
In release 3.0, this has been implemented:
```
            <xs:element name="Comments">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Comment" type="Comment" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Viewpoints">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ViewPoint" type="ViewPoint" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
```

**Comment by GeorgDangl** [comment]
I think this was addresses with #244.
