### ISSUE TITLE
"Stages" are lost in the new extensions.xsd

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#274]
From v2.1

![image](https://user-images.githubusercontent.com/3275463/104434905-16b9f480-558c-11eb-9468-43079c6df694.png)

**Comment by jasollien** [comment]
@ykulbak: I accidentially pushed the fix to release_3_0 branch. Please let me know if I should revert it

**Comment by jasollien** [comment]
https://github.com/buildingSMART/BCF-XML/commit/2d0a0ff8d82416eaffb4baacf2c8351076c94886

**Comment by ykulbak** [comment]
@jasollien thanks for noticing and fixing the issue.
