### ISSUE TITLE
Schema accepts non lowercase guids

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#278]

**Comment by jasollien** [comment]
![image](https://user-images.githubusercontent.com/3275463/106156036-58988c80-6181-11eb-8879-0c1fca69bd33.png)

From this discussion: https://github.com/buildingSMART/BCF-XML/issues/190, we decided that guids should be in lowercase.
However, upper case is still allowed in schema

**Comment by GeorgDangl** [comment]
Would you mind being assigned this? 😀
Looks pretty clear to me, I think we should update this.
