### ISSUE TITLE
Is topic status and topic type optional?

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-XML#285]

**Comment by LionelOnTech** [comment]
TopicType and TopicStatus marked as optional in https://github.com/buildingSMART/BCF-XML/tree/release_3_0/Documentation#topic, but should be mandatory based on schema.

**Comment by mattikannala** [comment]
The documentation is having ` Predefined list in “extension.xsd”` in multiple places.
The correct file name for the schema is **extension.xml**
