### ISSUE TITLE
Remove BIM snippet

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/BCF-XML#314]
BIM snippet has been in BCF since the very beginning, but is has never been used. We should remove it and if there's something in the future that requires such workload, we should add it later.

**Comment by berlotti** [comment]
Agree.

Snippets have originally been added to provide for 'changes in IFC'.  To get this really working in a CDE environment we need to change IFC first.

As long as this is not used, tested and figured out, it should not be in the standard (in any standard).
Removing it for 3.0 would be a good call.
Adding the functionality later, when dependency problems on IFC are resolved, and the other API projects are more mature, is a good thing.

**Comment by GeorgDangl** [comment]
While I agree on this, we should definitely discuss this in a bigger round😀

I haven't seen it used outside of some demo use cases, and I'm also not aware of any other serious use cases where the BIM Snippet is considered a viable way to implement a feature. However, I think it's a rather big change to introduce it so late in the process.

Let's use the next call to talk about this.

**Comment by ernTie** [comment]
What is the status of BIM snippet, are you planning on removing it ? 
We took a look at implementing BCF and think that there could be usecases for BIM snippet in infrastructure projects, which are not using IFC files.

**Comment by marwiss** [comment]
The idea "to modify an IFC-file" does however seem to be at least "theoretically possible", and I guess this hypothetical possibility could be the reason why this feature was originally added as a way of "future proofing" the BCF specification, ...even though no server or client ever implemented this feature, and even though "modifying IFC-files directly " is neither a possible nor a prefered way to work for most people.

To modify IFC-files using BIM sippets, the server would need to have its own IFC-file parser to create the instance graph, make the modifications according to the BIM-snippet, validate the new instance graph against the EXPRESS-scheme, and then export the instance graph into a new STEP-file. There would also have to be some kind of agreement on a standard (between clients and servers) on how to save "instructions about IFC-file modifications" in a BIM snippet. There is no such standard today.

**Comment by marwiss** [comment]
I was wondering if more software working natively in IFC (such as the relatively new Blender BIM) could make use of the BIM snippet feature.

Here is a whitepaper on native IFC.

https://github.com/brunopostle/ifcmerge/blob/main/docs/whitepaper.rst

For clients using native IFC (according to the whitepaper) it might be easy to implement the BIM snippet feature as intended.
