### ISSUE TITLE
ReferenceSchema is mentioned as "optional" in documentation, but is mandatory in XSD

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#339]
CC: @TestPrab who kindly brought this to my attention

For 2.1: https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/markup.xsd#L53
For 3: https://github.com/buildingSMART/BCF-XML/blob/release_3_0/Schemas/markup.xsd#L46

**Comment by GeorgDangl** [comment]
Thank you for raising this! It's been fixed😀
