### ISSUE TITLE
Field of view documentation

### ISSUE THREAD

**Issue by Moult** [buildingSMART/BCF-XML#344]
BCF 3.0 schema says the limit is 45-60, but it is actually 0-180. Perhaps to be reworded?

https://github.com/buildingSMART/BCF-XML/blob/release_3_0/Schemas/visinfo.xsd#L72

**Comment by GeorgDangl** [comment]
See https://github.com/buildingSMART/BCF-XML/commit/3ef27531019c199b83f324e07682ea84d937da06
