### ISSUE TITLE
BCF-XML validator

### ISSUE THREAD

**Issue by assaad97** [buildingSMART/BCF-XML#345]
hello, im new to BIM and BCF standards, and im currently buidling a 3D viewer based on xeokit-sdk, the sdk is working fine, one of the feature that im trying to implement, is generating and exporting bcf files, i respected while generating the bcf archive the order of the xml nodes in the files, the case of the nodes(PascalCase), and even sticked with only whats mandatory as elemnts in the archive, i used a python script from building smart to generate the guid, 

the probleme that im facing is that, the generated bcf, doesn't get imported in other viewers (such as bimcollabzoom or 3d repo), and i have no idea what not working 

im gonna leave a bcf generated by my code in this issue, i really want to know whats wrong in it, and i think it would be a good idea if there some kind of bcf validator.

thank you for  your help and time
[test_bcf_generated.bcf.zip](https://github.com/buildingSMART/BCF-XML/files/6638649/test_bcf_generated.bcf.zip)

ps : i imported it in here as a zip just because github have extension rstrictions.

**Comment by assaad97** [comment]
@GeorgDangl what im trying to say, is there any rules or standards from a software devlopement point of view that i need to respect while generating an BCF

**Comment by GeorgDangl** [comment]
Hey @assaad97, thank you for raising this issue!

There's a check tool available by @CBenghi: https://github.com/CBenghi/bcf-tool/

I just checked your file and it looks fine, the check tool didn't give any warnings. A brief manual inspection also didn't show anything unusual.

However, I think you might have made an error when zipping the file. BCF files themselves are zip archives that should have folders for all the topics in the file. However, in your archive, there was just a root level folder called `test.bcf`, so it looks like the structure might be off?

Other than that, I think that the author of Xeokit, Lindsay Kay, has some experience with creating BCF files from his viewer, so he might even have something ready for that?

**Comment by assaad97** [comment]
thank you so much @GeorgDangl for this information, i was zipping the folde dirrectly in windows and i think thats what was causing the problem, meaning that the zipping wasn't actually respecting the structure of a standard bcf file

again thank you for your help and if i have any issue i won't hesitate to share it with the community

**Comment by CBenghi** [comment]
I should update the tool to check for that type of problem.

It's mightly busy times, but I'll add it to my to-do.

Thanks

Il Ven 11 Giu 2021, 16:08 assaad ***@***.***> ha scritto:
