### ISSUE TITLE
Missing Topic Label

### ISSUE THREAD

**Issue by Wolgraph** [buildingSMART/BCF-XML#348]
Good morning. 
I'm thoroughly studying the code of this library for a project. As a reference I'm using a basi BCF file created with BCFManager within Revit.
As I created a topic I noticed I could assign the discipline (Architectural, Electrical, Mechanicalm Structural, ecc.)
In the BCF file this is stored as element of the Comment node as shown below:
```
<Topic Guid="8b71fd67-7e9a-4510-b5eb-26c65a896f6c" TopicType="Issue" TopicStatus="Active"><br>
		<Title>Fare tetto piano</Title><br>
		<Priority>Major</Priority><br>
		<Index>1</Index><br>
		<Labels>Architecture</Labels><br>
		<Labels>Structure</Labels><br>
		<CreationDate>2021-07-23T10:00:27+00:00</CreationDate><br>
		<CreationAuthor>email@address.123</CreationAuthor><br>
		<ModifiedDate>2021-07-23T10:00:46+00:00</ModifiedDate><br>
		<ModifiedAuthor>email@address.123</ModifiedAuthor><br>
		<AssignedTo>email@address.123</AssignedTo><br>
		<Description>Fare tetto piano</Description><br>
	</Topic>
```
But the `<Labels>` elements don't appear to have a definition class in the library. Am I missing something or is the library which still doesn't implement that?

**Comment by GeorgDangl** [comment]
Hey @Wolgraph, thank you for raising this issue!

I'm not sure I completely understand the issue. In BCF v2.1 (which I assume this file is), there's a schema definition for the element `Labels`:  
https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/markup.xsd#L66

That's what you're seeing here.

The values there aren't predefined - essentially, they're just string values. Some applications and BCF servers might impose rules for them, such as only using ones from a predefined list, but often they're really just free string values.

**Comment by Wolgraph** [comment]
Hi @GeorgDangl, thanks for answering.
What I mean is that I haven't found a definition for that element in _BCFTopic.cs_.

**Comment by GeorgDangl** [comment]
Where is that file coming from? This sounds like a C# source code file, so maybe there is an error with how the file was created. I don’t think it’s part of this repository.
