### ISSUE TITLE
Update README to include contact details for the cde group

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-XML#349]
We should have the openCDE@buildingsmart.org mail address somewhere in the document visible, ideally at the top and with a few words to explain when to reach out (not for technical support, but for getting in touch with the group).

See also https://github.com/buildingSMART/BCF-API/issues/276 in the API repo

**Comment by ykulbak** [comment]
Will need merging to both the `master` and the `release_3_0` branches.
