### ISSUE TITLE
Tools that support bcf 3.0

### ISSUE THREAD

**Issue by zominym** [buildingSMART/BCF-XML#352]
Hi,

I'm currently working on exporting data in BCF 3.0 format, however I can't seem to be able to find a tool to visualize this data (and check compatibility), or to export some data and compare.

Do you have a list of known tools that implement reading in 3.0 format?

I tried BCFIER and Trimble for example and they work well with 2.1, but not with 3.0.

I think Revit might work but it's not a free software...

Any help would be much appreciated.

**Comment by GeorgDangl** [comment]
Hey @zominym, thank you for raising this issue!

There's a list by buildingSMART that lists compatible software: https://technical.buildingsmart.org/resources/software-implementations/

Also, the wiki here has a similar list: https://github.com/buildingSMART/BCF-XML/wiki/Supporting-Applications

However, I think both lists are self-reported, so likely not be complete.
