### ISSUE TITLE
CameraViewPoint units

### ISSUE THREAD

**Issue by rubendel** [buildingSMART/BCF-XML#353]
I could not find this in the spec, examples seem to be using meters, but I'd like to know for sure.

Does it have to be in:
- Meters
- Millimeters
- Same as what's defined in the referenced IFC file's LENGTHUNIT

**Comment by ykulbak** [comment]
@rubendel thanks for raising this issue, I believe its meters. Can you please raise a pull request to add this information to the spec?

**Comment by rubendel** [comment]
Thanks, sure can do: https://github.com/buildingSMART/BCF-XML/pull/354
