### ISSUE TITLE
Topic GUID mismatch

### ISSUE THREAD

**Issue by sminjard** [buildingSMART/BCF-XML#358]
Hi,

In version 3.0, it is said that 

> The folder name is the GUID of the topic

Yet in the Test Cases, there is a file (at least) that does not follow this rule : 
> Test Cases/v3.0/Visualization/Single invisible wall/single invisible wall.bcf
https://github.com/buildingSMART/BCF-XML/blob/release_3_0/Test%20Cases/v3.0/Visualization/Single%20invisible%20wall/unzipped/e1fff3a6-db0f-48e8-a240-0e2f38b2fc21/markup.bcf

As you can sse the guid inside the file and the guid as name of the folder do not match. My question is : which one takes priority over the second one in this case?

**Comment by ykulbak** [comment]
Thanks @sminjard 

@jasollien can you please confirm the issue and propose a pull request to fix it?

**Comment by GeorgDangl** [comment]
So the folder needs to be renamed to `d5121f1c-11e0-4f25-9d23-7ace76853a8f` to match the id of the topic.

**Comment by sminjard** [comment]
> So the folder needs to be renamed to `d5121f1c-11e0-4f25-9d23-7ace76853a8f` to match the id of the topic.

If we consider that the correct id is the one inside the topic, yes.

**Comment by GeorgDangl** [comment]
Done in #377
