### ISSUE TITLE
proposal: adding "GeoPoint"

### ISSUE THREAD

**Issue by PerspectivesLab** [buildingSMART/BCF-XML#360]
hi there, could this be considered for the next version ?
https://github.com/buildingSMART/BCF-API/issues/307
geopoint could be used in the industry for real world annotation mapping

**Comment by ykulbak** [comment]
@PerspectivesLab of course it could be considered. Please be aware that there's no timeline yet for the next version,

**Comment by GeorgDangl** [comment]
Tracking this in the BCF API repo: https://github.com/buildingSMART/BCF-API/issues/307
