### ISSUE TITLE
How to save the GUID of an IfcElementType in a bcf file

### ISSUE THREAD

**Issue by Martin15135215** [buildingSMART/BCF-XML#365]
With those two files i created with [IfcTester ](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifctester) a bcf report:

[buildingSMART/IDS@master/Documentation/library/sample.ids](https://github.com/buildingSMART/IDS/blob/master/Documentation/library/sample.ids?rgh-link-date=2023-08-07T06%3A18%3A54Z)
[buildingSMART/IDS@master/Documentation/library/sample.ifc](https://github.com/buildingSMART/IDS/blob/master/Documentation/library/sample.ifc?rgh-link-date=2023-08-07T06%3A18%3A54Z)

However since one of the specification had something to do with a IfcWallType, the GUID of the IfcWallType was not saved in the bcf report, since only in the viewport can the GUID from a ifc entity be saved. Unfortunately the IfcWallType had no geometry.

How can you still store the GUID so that you can select this entity in a BCF app?

**Comment by GeorgDangl** [comment]
Hey @Martin15135215, thanks for raising the issue!

At the moment, this is not something that's supported by BCF, components that are referenced in an issue are always concrete instances. We can not address types at the moment.

But, if there's a practical use case for this, we can certainly start a discussion around this.
