### ISSUE TITLE
Invalid test cases in v2.1 w.r.t. Comment

### ISSUE THREAD

**Issue by thbeu** [buildingSMART/BCF-XML#381]
The following test cases in the [release_2_1](https://github.com/buildingSMART/BCF-XML/tree/release_2_1) branch violate the [markup.xsd](https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Schemas/markup.xsd) because of the missing  `Comment` element inside `Comment`. Additionally, they do not seem proper elements of v2.1 at all due to legacy elements `VerbalStatus`, `Status` and `Topic`.

https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Test%20Cases/v2.1/Visualization/Single%20visible%20space/unzipped/a3befb7d-8395-4e52-bbca-382fc4198217/markup.bcf#L11-L17

https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Test%20Cases/v2.1/Visualization/Single%20visible%20wall/unzipped/d029895e-2bdc-4f48-8bf4-8e540425f238/markup.bcf#L12-L18

https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Test%20Cases/v2.1/Visualization/single%20invisible%20wall/Unzipped/e1fff3a6-db0f-48e8-a240-0e2f38b2fc21/markup.bcf#L11-L17

https://github.com/buildingSMART/BCF-XML/blob/d67e2a16425f4740182084bba4c937b1b36198c1/Test%20Cases/v2.1/Visualization/all%20components%20and%20spaces%20visible/unzipped/2c02d25f-6cb7-4c14-8737-9c340699d351/markup.bcf#L11-L17

**Comment by GeorgDangl** [comment]
Thank you for the issue!

We've already fixed this some years ago: https://github.com/buildingSMART/BCF-XML/commit/58b3da4b2f087f887cfbf4921451f6df1163b3a7

We didn't backport it to the old branch, because we've fixed it as a tag when v2.1 was released.

**Comment by thbeu** [comment]
The issue with such non-backported fixes is, that there is **no** valid 2.x maintenance branch/releases, and tools are unable to create schema-conform v2.1 XML files. This seems odd.
