### ISSUE TITLE
Draw Revision cloud in shapshot 

### ISSUE THREAD

**Issue by RyugaRyuzaki** [buildingSMART/BCF-XML#385]
Is there way to draw a revision cloud in snapshot of viewpoint and add to viewpoint.bcfv ?
```
<Annotation>
            <Cloud>
                <Vertices>
                    <Vertex>
                        <X>...</X>
                        <Y>...</Y>
                        <Z>...</Z>
                    </Vertex>
                    ...
                </Vertices>
            </Cloud>
</Annotation>
```

**Comment by GeorgDangl** [comment]
Hey @RyugaRyuzaki, thank you for the issue!

As far as we can tell, this should be exactly what's offered by the current `Lines` feature. So, we support that😀

**Comment by GeorgDangl** [comment]
https://github.com/buildingSMART/BCF-XML/blob/release_3_0/Schemas/visinfo.xsd#L18
