### ISSUE TITLE
Documentation error for Topic GUID

### ISSUE THREAD

**Issue by gliderguy** [BuildingSMART/BCF-XML#50]
Version 2.0 Technical Documentation for markup.xsd says that a GUID is optional for a Topic attribute and a GUID element is required as an element of Topic.  The schema only supports a mandatory GUID attribute for Topic. No GUID element is specified within Topic.

**Comment by LionelOnTech** [comment]
I believe I can clarify. If you navigate to [https://github.com/BuildingSMART/BCF/tree/master/Documentation#topic], you will notice that the GUID is documented as Optional = Yes. The issue is that the Readme.md does not match the XSD.
