### ISSUE TITLE
Latest viewpoint and snapshot to be used for compatibility

### ISSUE THREAD

**Issue by jlkiss** [BuildingSMART/BCF-XML#53]
In the documentation you can read this:
"One viewpoint needs to be be named viewpoint.bcfv even in the case of multiple viewpoints."
"One snapshot needs to be named snapshot.png even in the case of multiple viewpoints."

I think for compatibility it is the best if we export the viewpoint and snapshot of the latest/newest comment with fixed "viewpoint.bcfv" and "snapshot.png" names. (Not a random viewpoint/snapshot).
What do you think?

**Comment by ErikPijnenburg** [comment]
It is best to keep the oldest viewpoint of an issue in that default name, never change that later on when adding viewpoints. This way we have
1) a clear view on what can be defined as a 'default' viewpoint (=the viewpoint/snapshot the issue is recognized by / created by = the oldest one). 
2) backward compatibility with BCF 1.0

**Comment by teocomi** [comment]
I think a prescription about which view (viewport&snapshot) should use the "old" naming is unnecessary: what happens when the "default" view is deleted?
Instead, an ordinal for the views would be really useful.

**Comment by ErikPijnenburg** [comment]
An ordinal number would change the definition; so earliest for next version. Btw  the order is already available via history of comments were the Viewpoints are linked to.

**Comment by jlkiss** [comment]
Erik,

1. If we would keep the oldest viewpoint in the default (compatibility) name, no new view information can be transferred to and from BCF 1.0 compatible applications. If we export the latest viewpoint in the default name, some of the view information can be exchanged between BCF1.0 and BCF2.0 applications during export rounds.
2. Backward compatibility does not depend on using either the latest or the oldest viewpoint. It depends on that we export one of the views with the previous version's file names.

**Comment by ErikPijnenburg** [comment]
I think it is useles to try getting a reliable workflow with BCF 1.0 files with backward compatibility. There are worse problems then this one mentioned here. Like missing viewpoints, unreliable status changes, unknown modification dates/authors and thus unreliable merging = unreliable issue management.
Let's hope applications update to BCF 2.0 asap.
