### ISSUE TITLE
Feature request: ordinal for issues and views

### ISSUE THREAD

**Issue by teocomi** [BuildingSMART/BCF-XML#54]
[Updated]
Feature request 1: possibility to sort issues within a BCF file. 
Feature request 2: possibility to sort the views (viewpoints&snapshots) within an issue.

The user  needs to be able to sort these in a custom order that is not just chronological or alphabetical, for presentation purposes and much more.

This implementation for the views could be easily done by adding an ordinal field in the `<xs:complexType name="ViewPoint">`.
For the issues, it could either live in the "project.bcfp" file, in  a new "issues.bcfi" file, or in the `<xs:element name="Markup">` (probably worst approach).

**Comment by gschleusner** [comment]
I certainly would like to see this, but I think we need more info to make it useful.  I brought this up last year, but I'd very much to see a "relations" payload, that captures data independent of the issues them selves.  This way you could actually use an independent tool to sort, group and organize the results independent of the tools that generated the results, sorting and prioritizing would be an obvious add.

https://drive.google.com/folderview?id=0B8WWWkKd48yASzBDbVpTMUQ2aXM&usp=sharing

**Comment by ErikPijnenburg** [comment]
Matteo: in #35 you argue not to have sub discussions and multiple issues inside one issue by adding multiple viewpoints (on whch I agree). But in this topic you seem to suggest to sort issues & viewpoint inside issues, but that means having mutiple issues inside one issue?
I rather follows Greg's approach to build relations between issues, preferable automaticly found by checkers with smart analysis-tools. BCF 2.0 already has room for defining relations between issues. Perhaps one of the Model Checker guys could share there view on how to improve this? Pasi ?

**Comment by teocomi** [comment]
Erik, I haven't explained myself clear enough:

Feature request 1: possibility to sort issues within a BCF file. 
Feature request 2: possibility to sort the views (viewpoints&snapshots) within an issue. 

I like the idea of issues relations.

**Comment by ErikPijnenburg** [comment]
Aha, thanks for explaining Matteo. 
1)
I like the idea of using the projectfile to sort issues in the file but propose to use index-nr for that. Then it can be simply done by listing in the project-file the issue-index-nrs + GUIDs.
2)
We have no need for this: we sort comments always chronological (like here in github and other issuetrackers) and show related viewpoints next to them.
