### ISSUE TITLE
Future improvement: an optional list of custom identifiers for File elements in the Header

### ISSUE THREAD

**Issue by ykulbak** [BuildingSMART/BCF-XML#59]
## Purpose
This improvement would allow different tools to safely store a mappings between models and issues. If implemented properly then when a BCF is displayed the tool will be able to confidently lookup the models related to the BCF, load them and then apply the BCF viewpoint and display the topic.

## Proposal
For each File element add an optional list of custom identifiers where each identifier has the following elements:
* vendor name
* system name
* id

> The various vendors and BIM servers supporting BCFs would have to keep each other's identifiers and only add/remove their own identifiers if needed

## Example

In the example below, Vendor1 is used by a couple of users so there's unique identifiers for both their desktops, Vendor2 is used by another user and there's also a central BIM server that stores the models as well as the BCFs which embeds it's UIDs in each topic that is managed by it.

```
<Header>
   <File>
      <Filename>some file.ifc</Filename>
      <Date>...</Date>
      <Reference>....</Reference>
      <CustomIdentifiers>
          <CustomIdentifier>
               <vendor>Vendor1</vendor>
               <system>User1's desktop ID</system>
               <id>some GUID that allows finding the file in the user's desktop</id>
          </customIdentifier>
          <CustomIdentifier>
               <vendor>Vendor1</vendor>
               <system>User2's desktop ID</system>
               <id>some GUID that allows finding the file in the user's desktop</id>
          </customIdentifier>
          <CustomIdentifier>
               <vendor>Vendor2</vendor>
               <system>User3's desktop ID</system>
               <id>some GUID that allows finding the file in the user's desktop</id>
          </customIdentifier>
          <CustomIdentifier>
               <vendor>BimServer1</vendor>
               <id>some GUID that allows finding the model on the BIM Server</id>
           </customIdentifier>
      </CustomIdentifiers>
  </File>
  <File>
      ....
  </File>
  .....
```

**Comment by GeorgDangl** [comment]
Accepted for 2.1 / -> Need PR for XML and API

**Comment by linhard** [comment]
#87
