### ISSUE TITLE
Future improvement: explicit ordering of viewpoints

### ISSUE THREAD

**Issue by ykulbak** [BuildingSMART/BCF-XML#60]
##  Purpose
Consistent presentation of topics in different tools through explicit ordering of viewpoints.

## Proposal

BCF allows connecting viewpoints with comments and also to have viewpoints 'floating' at the topic level. When all the viewpoints are attached to comments then the comment's date can be used to choose how to order the viewpoints when displaying them to the user.
However, the user is not able to choose a different order nor is she able to order 'floating' viewpoints so that their display order is consistent among different tools.

### The following changes are proposed:
1. Add an optional 'index' attribute for each ViewPoint 
2. Specifying that  when ViewPoints are not indexed then the order in which they appear in the XML should be used to display them to the user 
3. The viewpoint ordering and index should be preserved by a BCF compliant tool

> The first ViewPoint is most important since it's snapshot is used, by many tools, to generate the thumbnail for the topic. Today, users can't choose which ViewPoint will represent the topic or change their mind if they made a mistake.

**Comment by teocomi** [comment]
Related to #54
