### ISSUE TITLE
Future improvement: DueDate

### ISSUE THREAD

**Issue by linhard** [BuildingSMART/BCF-XML#61]
A BCF topic has a "CreatedDate" and a "ModifiedDate" but we has not something like a "DueDate" what means a date up to when the topic should be solved

**Comment by DuncanLithgow** [comment]
But those two dates relate to the issue being added to the bcf system, they are not "real world" dates. To add a due date creeps us towards being a project resources management solution. I think this is out of the scope of the intent of bcf. 

Rather see how data connections to such management software can work.

**Comment by linhard** [comment]
#79
