### ISSUE TITLE
Feature request: Support for multiple viewpoints in BCF comment

### ISSUE THREAD

**Issue by venilillkall** [BuildingSMART/BCF-XML#70]
Note models of Tekla products often allow multiple viewpoints/snapshots per comment. 
This is not supported by the BCF 2.0 release schema, a prerelease schema we used earlier allowed this. We were using the feature, I really wonder why it was dropped? 

In documentation the restriction is stated: 
"One to Many Mapping between Viewpoints and Comments 
The schema would allow to have many to many mapping between viewpoints and comments. This is not allowed. A viewpoint can have multiple comments, but a comment can only refer to one viewpoint." 

Would it be possible to allow unbounded viewpoints within a comment, the current schema defines max 1.

(origin: http://jira.buildingsmart.org/browse/BCF-26)

**Comment by PARKJUNGSUP** [comment]
Hello. I have a question. 
The element [Viewpoint] in the element [Comment] was defined by optional. Here is Markup that has two [Viewpoints] and one [Comment]. [Viewpoint] was elided in [Comment]. In this case, how can I know [Comment] reference to any [Viewpoints]?
If the element [Viewpoint] is not optional, I didn't think about this case.

**Comment by PARKJUNGSUP** [comment]
Hello. I have a question. 
The element [Viewpoint] in the element [Comment] was defined by optional. For example, I export the bcfzip using Solibri Checker 9.6,  create two element [Viewpoints] without any comment. In markup.bcf, the element [Comment] was created but the element [Viewpoint] was elided. In this case, how can I know [Comment] reference to any [Viewpoints]?
If the element [Viewpoint] is not optional, I didn't think about this case.

**Comment by GeorgDangl** [comment]
See #82
