### ISSUE TITLE
Future improvement: DocumentReferences and RelatedTopics element names unnecessarily in plural

### ISSUE THREAD

**Issue by venilillkall** [BuildingSMART/BCF-XML#72]
In markup.xsd. Notice! These are the repeating, not container elements. There are couple of similar issues. I assume the current situation is not intentional(?). I realize changing this will break compatibility with existing standard. Included in pull request https://github.com/BuildingSMART/BCF-XML/pull/64

(origin: http://jira.buildingsmart.org/browse/BCF-25)

**Comment by GeorgDangl** [comment]
See #64
