### ISSUE TITLE
Missing extension and contenttype in the 2.0 documentation

### ISSUE THREAD

**Issue by rubendel** [BuildingSMART/BCF-XML#73]
Hello, in the 2.0 documentation I am missing:
- The file extension (.bcfzip), it is mentioned somewhere halfway in the document under "DocumentReference" though I'd expect it in the beginning of the document.
- The content type that should be used ("application/zip", or something else?)

**Comment by linhard** [comment]
#88

**Comment by rubendel** [comment]
Thanks, I can't find anything about the Content-Type in the documentation or issue #88 though.

**Comment by GeorgDangl** [comment]
I think we can safely use `application/zip` for the BCF XML files. They're not primarily intended to be downloaded via web servers (that's what the API is for), so using the standard mime type for zip files should be ok.
