### ISSUE TITLE
BCF 2.1: Consider changing the BCF file extension to clearly distinguish it from BCF 2.0

### ISSUE THREAD

**Issue by ykulbak** [BuildingSMART/BCF-XML#84]
Since it is likely that BCF 2.1 will have backward incompatible changes like viewpoint encoding we should consider using a new file extension so that clients that don't support it would be mislead and attempt to load it.

**Comment by GeorgDangl** [comment]
Accepted for 2.1 / Decided to use `.bcf21`

**Comment by linhard** [comment]
#88

**Comment by lbj** [comment]
I find this a rather odd decision. Why not simply use the version part of the schema? IFC seems to do quite well from version to version without changing the file extension. So do pdf, dwg and lots of other formats that does not necessary stay backwards compatible.

**Comment by ErikPijnenburg** [comment]
I agree with Lars

**Comment by ErikPijnenburg** [comment]
This issue should be reopened

**Comment by ykulbak** [comment]
@ErikPijnenburg can you please join the next Telecon to discuss your concerns?

**Comment by ErikPijnenburg** [comment]
I will try to join next telecon, or otherwise Pieter will be there.
If we decide for another extension we definitally should make it version independent. Otherwise we end up having extensions for each version...

**Comment by GeorgDangl** [comment]
Reopened for further discussion

**Comment by GeorgDangl** [comment]
We've changed the extension, so I'm closing this issue.
