### ISSUE TITLE
Feature proposal: Adding (e.g."marker pin-like") icon for BCF topics at freely-chosen location in the 3D model viewer

### ISSUE THREAD

**Issue by mullerlele** [buildingSMART/BCF-XML#86]
## Background

Tekla BIMsight already offers a great feature in displaying the BCF topics with a small "comment-like" icon in its 3D viewer ([screenshot](http://i1-win.softpedia-static.com/screenshots/Tekla-BIMsight_1.png)). However, it seems that the icon is always placed at the centroid of (one of) the selected component(s)/element(s) in the ifc 3D model. The icons would overlap and eclipse each other, when user creates multiple BCF topics on the same selected ifc component(s). 

Another limitation emerges, when two (or multiple) separate BCF topics have to be associated to different part of the same selected component(s) (e.g. one topic is related to the top of a wall, yet another one is related to the foot of the wall.). Ideally, in this case, it would be great to have multiple icons placed at different locations of the same selected component(s) in the 3D model viewer.  

In order to boost the user interaction with 3D model to a higher degree of freedom in the viewer, we propose to accommodate the world coordinates of the icon for BCF topics in the next version of the BCF schema. 
## Technical Approach

When creating a new BCF topic, the user will have the opportunity (i.e. optional) to pick the location of the icon in the 3D model viewer (e.g. where the mouse click intersects with the 3D model). The world coordinates of the pick will be then saved in the BCF files. 
## Proposal of the Update in the BCF Schema

Addition of "TopicPinWorldCoordinates" in the visinfo.xsd (indicated below by '+++') 

```
...

<xs:complexType>
            <xs:sequence>
                <xs:element name="Components" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Component" type="Component" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="OrthogonalCamera" type="OrthogonalCamera" minOccurs="0"/>
+++             <xs:element name="TopicPinWorldCoordinates" type="Point" minOccurs="0" maxOccurs="1"/> +++

... 
...

            </xs:sequence>
</xs:complexType>

...

```

**Comment by emrazek** [comment]
Generally I would say pin is a good idea. it's much more precise to point out to the real problem like just by selecting a whole element (e.g. you have a column and basement and you want to point out to some problem in connection part etc. etc. ) The question is if for one issue only one Pin should be allowed or not. If yes, than above mentioned proposal is OK. But if not (what from my point of view is more logical) than maybe a list of Pins (none mandatory new field "x,y,z, direction vector") is the better idea, 'cos than no Pin is not connected directly to the view and is up the client how will handle it when e.g. user will select the concrete Pin. (e.g. in bim+ we are zooming to this pin and optional we can set all the other elements to transparent to see also pins inside structure etc.) But it's up the client how they proceed it. BCF from my point of should only provide a message and not to push the client how to manage/process it.
From that point of view I would say Pin(s) should a list of new separate none mandatory array of the coordinates and direction vectors in the BCF definition.
The next thing to consider is if Pin should have also relation to the element. I would day yes, 'cos if e.g. element is deleted (e.g. by model update) than also Pin should be automatically deleted, a Pin in the air makes no sense.  So the next parameter in the Pin definition should be an IFC UUID.

**Comment by mullerlele** [comment]
After many rounds of discussion and review in house, which involved investigating into the potential use cases and the effort of implementation in authoring tools like Revit and Sollibri, we have decided to modify our proposal as follows:

We no longer require the addition of a customized field ("TopicPinWorldCoordinates") to the BCF standard. Instead, we would like to employ one of the existing fields in the BCF standard to carry the pin location information. As there are "Lines" elements already defined in the BCF standard, it would still be mathematically correct if we would use it for defining a "Point" (or more precisely, the point for the pin in this case).

When the "StartingPoint" and the "EndPoint" are identical for the "Line" element (i.e. a line of zero length), we would then define this particular "Line" element to be the carrier of the pin location information (enclosed by the  <xs:sequence> tag). Here I include the definition of the "Line" element in the visinfo.xsd below just for reference:  

```
<xs:element name="Lines" minOccurs="0">
          <xs:complexType>
                       <xs:sequence>
                           <xs:element name="Line" type="Line" maxOccurs="unbounded"/>
                       </xs:sequence>
          </xs:complexType>
</xs:element>

<xs:complexType name="Line">
         <xs:sequence>
                       <xs:element name="StartPoint" type="Point"/>
                       <xs:element name="EndPoint" type="Point"/>
         </xs:sequence>
</xs:complexType>

```

We would like to propose including the explanation above (in better technical writings maybe) in the Implementation Agreements section of the BCF-XML documentation, if the everyone deems necessary.

**Comment by gschleusner** [comment]
I certainly think having an exact location for an issue would make the current standard better.  If the line approach is best I do not know.  The one thing I'll point out is that in the future it would be logical if you could associate an issue with a real world location.  For uses within infrastructure and in operations. So having a "TopicLocation" that can contain a xyz and a lat,lon would seem to be a good concept to bring forward.

**Comment by ErikPijnenburg** [comment]
Using lines for this in the proposed way is a rather 'ugly' solution. If we want to add a location it deserves it's own property, indeed a 'Point'. When defined in visinfo it will be not a TopicLocation but a ViewpointLocation, since then each viewpoint can have it's own location.

**Comment by gernotewert** [comment]
From my point of view pins need to be managed separately in an extra list within the topic. Additional it should reference to the component it is attached to. --> If I change the visibility of the scene I want to be able to also reduce the amount of pins or color those, according to the visible elements or on filtering the topics, e.g by priority.

**Comment by GeorgDangl** [comment]
This is still being tracked for BCF 3.0.

**Comment by pasi-paasiala** [comment]
See also https://github.com/buildingSMART/BCF-XML/issues/86
