### ISSUE TITLE
Create section for example implementations and list of products supporting BCF

### ISSUE THREAD

**Issue by GeorgDangl** [BuildingSMART/BCF-XML#91]
As per the discussion of #89 in todays telecon, it was decided to not include links to products or open source code repositories in the official documentation here on GitHub. We'll have to move that somewhere else, for example to GitHub pages, a Wiki or maybe pin it to the top in the Google Group.

This should be finally decided in next weeks call.

**Comment by linhard** [comment]
Agreed that we will have a BCF entry on Wikipedia #93
