### ISSUE TITLE
[not an issue] BCF entry on Wikipedia

### ISSUE THREAD

**Issue by DuncanLithgow** [buildingSMART/BCF-XML#93]
Sorry for posting this here, but I don't know where else to post it.

I've made a start on a BCF entry for wikipedia. Because the subject is rather obscure we will need to focus on the notability[1] of BCF by citing good sources and referencing other relevant links.

You can find the page as part of my own page on wikipedia https://en.wikipedia.org/wiki/User:DuLithgow#BIM_Collaboration_Format which anyone can edit, also without loggin in.

Feel free to check ti out, edit it, or just write to me what you think could be improved. I'll make sure the formatting and setup is correct before making it live.

[1] Notability of a subject is a requirement for any wikipedia entry. More about that here
: https://en.wikipedia.org/wiki/Wikipedia:Notability

**Comment by linhard** [comment]
Very good !
List of BCF Products (Commercial Products, Open Source) and their supporting version(s) could/should also be there as well as links to literature like research projects, theses, ....
@Duncant -> maybe you could add chapters for that where the group then can add their links.

**Comment by DuncanLithgow** [comment]
I've added a bit of text giving space for more software mentions. Feel free to edit the text...

**Comment by DuncanLithgow** [comment]
https://en.wikipedia.org/wiki/BIM_Collaboration_Format
https://no.wikipedia.org/wiki/BIM_Collaboration_Format
